---
name: Reusable unit test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        attempt: [1,2,3,4,5,6,7,8,9,10]
    runs-on: actuated-arm64-2cpu-4gb
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"

      - name: Look into the tool cache before setup-go
        run: |
          find /home/runner/actions-runner/_work/_tool/ -name go | grep bin
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
          cache: false
          check-latest: false

      - name: Look into the tool cache after setup-go
        run: |
          find /home/runner/actions-runner/_work/_tool/ -name go | grep bin

      - name: Find where go was put
        run: |
          which go

      - name: Run tests
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
