---
name: Reusable unit test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  test-linux:
    strategy:
      fail-fast: false
    runs-on: actuated-arm64-2cpu-4gb
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
          cache: false
          check-latest: false

      - name: Run tests
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
